### ISSUE TITLE
allow anonimous acess to JIRA API

### ISSUE THREAD

**Issue by melezhik** [packy/JIRA-REST-Class#2]
Sometimes if one access public JIRA API he does it anonymously, without credentials being added. Looks like   JIRA-REST-Class implies a credentials should be set?

**Comment by packy** [comment]
Actually, that requirement comes from JIRA::REST. When I was trying to fetch some information from Atlassian's public JIRA (before I ponied up the $10 run my own at home), I had created a child class for JIRA::REST that allowed anonymous use, but I wound up having to override more methods than just "new" (which is where the authentication header is constructed), so I was nervous about including it in my published module. 

I thought about requesting an enhancement for JIRA::REST to allow anonymous use, but I wasn't sure if I was the only one who would want it. I see I'm not. 

I'll ask that module's author about it. If he isn't receptive to an enhancement, I'll work on that subclass that I had.

**Comment by melezhik** [comment]
Ahh, Ok. this is only like an idea. Not is "requirement" . As allowing anonymous access  would make it possible to test JIRA-REST-Class against any other public JIRA API to check compatibility . But if you are not going for a such "expansion" , that's ok ))) You may close this issue ....

**Comment by packy** [comment]
No, I'd love to have that expansion.  I just wasn't sure if I was the only person interested in this kind of usage.  Being able to test the module against public JIRA APIs is a definite plus.

**Comment by melezhik** [comment]
Well, the root of my question is I am the author of [Sparrow](https://metacpan.org/pod/Sparrow) - an automation/testing framework. I like to see others modules CPAN and contribute by writting new tests for them based on Sparrow. When I started a new one  test for JIRA-REST-Class I have encountered this issue, probably I will come up with PR soon so you can see how one can test JIRA-REST-Class against public JIRA server ....

**Comment by melezhik** [comment]
here it is - https://github.com/packy/JIRA-REST-Class/pull/3

**Comment by packy** [comment]
**NOTE:** I'm leaving this open until JIRA::REST v0.017 is released, which will support anonymous use of JIRA servers that allow it.  It's working in 0.016, but that's a dev release, so I'm leaving the issue open until it's officially released.

**Comment by melezhik** [comment]
Hi @packy ! Sure! Thanks.
