### ISSUE TITLE
cpan isn't indexing the latest versions of JIRA::REST::Class

### ISSUE THREAD

**Issue by mannih** [packy/JIRA-REST-Class#4]
I noticed that you updated this module and tried to install the updates, but cpanm said I was up to date with version 0.03.
It seems that cpan doesn't support this:
```use JIRA::REST::Class::Version qw( $VERSION );```
See also http://www.cpan.org/modules/04pause.html#version

**Comment by packy** [comment]
Yeah, I noticed that immediately. It's getting fixed in a new version soon
(hopefully later today).

**Comment by mannih** [comment]
OK, Cool. So let's just pretend that nothing happened.
Thank you!
